CFLAGS  += -I/opt/quanser/hil_sdk/include
LDFLAGS += -L/opt/quanser/hil_sdk/lib
LIBS    += -lhil -lquanser_runtime -lquanser_common -lpthread -ldl -lm -lc -framework cocoa

hil_task_write_example: hil_task_write_example.o
	$(CC) $(LDFLAGS) $< -o $@ $(LIBS)

hil_task_write_example.o: hil_task_write_example.c hil_task_write_example.h
