CFLAGS  += -I/opt/quanser/hil_sdk/include
LDFLAGS += -L/opt/quanser/hil_sdk/lib
LIBS    += -lhil -lquanser_runtime -lquanser_common -lpthread -ldl -lm -lc -framework cocoa

hil_write_buffer_example: hil_write_buffer_example.o
	$(CC) $(LDFLAGS) $< -o $@ $(LIBS)

hil_write_buffer_example.o: hil_write_buffer_example.c hil_write_buffer_example.h
